version: "3"
services:
  app:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MEMCACHED_HOST=memcached
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/flask-app
  memcached:
    image: "memcached:alpine"